image: node:18-alpine

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - npm install
    - npx eslint . --fix

startup_test:
  stage: test
  script:
    - npm install
    - npm run dev 